build: false

services:
  - postgresql

environment:
  # There is no need to run the build for all the Python version /
  # architectures combo as the generated nilearn wheel is the same on all
  # platforms (universal wheel).
  # We run the tests on 2 different target platforms for testing purpose only.
  # We use miniconda versions of Python provided by appveyor windows images
  matrix:

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"

install:
  # Prepend miniconda installed Python to the PATH of this build
  # Add Library/bin directory to fix issue
  # https://github.com/conda/conda/issues/1753
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%"
  - conda update conda -y -q
  - conda create -n testenv --yes python=%PYTHON_VERSION% pip
  - conda env update -n testenv -f environment.yml
  - activate testenv
  - cd ramp-frontend && pip install -e .
  - cd ..
  - cd ramp-database && pip install -e .
  - cd ..
  - cd ramp-engine && pip install -e .
  - cd ..
  - cd ramp-utils && pip install -e .
  - cd ..

test_script:
  - SET PGUSER=mrramp
  - SET PGPASSWORD=mrramp
  - psql -U postgres -c "CREATE USER mrramp WITH PASSWORD 'mrramp';ALTER USER mrramp WITH SUPERUSER;"
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb databoard_test
  - pytest -rvsl .
