# This is the testing environment.
name: testenv
dependencies:
  - numpy
  - pyyaml
  - sqlalchemy
  - psycopg2
  - pandas
  - scikit-learn
  - Flask
  - Flask-Login
  - Flask-SQLAlchemy
  - Flask-Wtf
  - unidecode
  - termcolor
  - pytest
  - pytest-cov
  - flake8
  - jupyter
  - gitpython
  - scikit-image
  - bokeh
  - matplotlib
  - pycrypto
  - ipykernel
  - bcrypt
  - invoke
  - pip:
    - git+https://github.com/paris-saclay-cds/ramp-workflow
    - Flask-Shelve
    - Flask-Openid
    - Flask-Mail
    - pytest-env
    - xkcdpass
    - backports.tempfile  # remove when dropping Python 2 support
