# This is the testing environment.
name: testenv
dependencies:
  - bcrypt
  - bokeh
  - click
  - flake8
  - Flask
  - Flask-Login
  - Flask-SQLAlchemy
  - Flask-Wtf
  - gitpython
  - invoke
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - pyyaml
  - pytest
  - pytest-cov
  - psycopg2
  - six
  - sqlalchemy
  # some of the packages below should not be required
  # - unidecode
  # - termcolor
  # - pycrypto
  - pip:
    - backports.tempfile  # remove when dropping Python 2 support
    - git+https://github.com/paris-saclay-cds/ramp-workflow
    - Flask-Mail
    - pytest-env