# This is the testing environment.
name: testenv
dependencies:
  - bcrypt
  - bokeh
  - boto3
  - click
  - flake8
  - Flask
  - Flask-Login
  - Flask-SQLAlchemy
  - Flask-Wtf
  - gitpython
  - itsdangerous
  - nbconvert
  - numpy
  - pandas
  - scikit-image
  - pyyaml
  - pytest
  - pytest-cov
  - psycopg2
  - sqlalchemy
  - tornado==5.1.1  # downgrade tornado for nbconvert and should be fix
  - werkzeug<=1.0.0
  - pip:
    - codecov
    - ramp-workflow
    - Flask-Mail
