ramp:
    problem_name: <problem name>
    event_name: <name>
    event_title: "Human readable event name to display on website"
    event_is_public: true
worker:
    worker_type: <conda or aws>
    ...