ramp:
    problem_name: <problem name>
    event_name: <name>
    event_title: "Human readable event name to display on website"
    event_is_public: true
    data_dir: /tmp/databoard_test/ramp-data/<problem name>
    kit_dir: /tmp/databoard_test/ramp-kits/<problem name>
    submissions_dir: /tmp/databoard_test/submissions
    predictions_dir: /tmp/databoard_test/preds
    logs_dir: /tmp/databoard_test/log
    sandbox_dir: starting_kit
worker:
    worker_type: <conda or aws>
    ...